#include <DeviceDescription.hpp>

#include <memory>

#include "gtest/gtest.h"

namespace {

// Independent CRC32 implementation, so the tests cross-check the one in
// DeviceDescription.cpp rather than depending on it.
uint32_t TestCrc32(const uint8_t *data, uint32_t length) {
  uint32_t crc = 0xFFFFFFFF;
  for (uint32_t i = 0; i < length; i++) {
    crc ^= data[i];
    for (uint8_t bit = 0; bit < 8; bit++) {
      crc = (crc & 1) ? (crc >> 1) ^ 0xEDB88320 : crc >> 1;
    }
  }
  return crc ^ 0xFFFFFFFF;
}

// Recomputes and stores the CRC, for building deliberately malformed blobs
// that should be rejected for reasons other than the CRC.
void FixCrc(uint8_t *blob) {
  uint32_t crc = TestCrc32(blob, 28);
  blob[28] = crc & 0xFF;
  blob[29] = (crc >> 8) & 0xFF;
  blob[30] = (crc >> 16) & 0xFF;
  blob[31] = (crc >> 24) & 0xFF;
}

}  // namespace

TEST(DeviceDescription, serializeRoundTripsMultipleStripsAndFlags) {
  const DeviceDescription original(
      2350, {
                StripDescription(50, {Circular}),
                StripDescription(12, {Tiny, Circular, Mirrored}),
                StripDescription(96, {Dim, Reversed}),
            });

  uint8_t blob[DeviceDescription::kSerializedSizeV1];
  ASSERT_TRUE(original.SerializeV1(blob));

  std::unique_ptr<DeviceDescription> parsed(DeviceDescription::FromV1(blob));
  ASSERT_NE(parsed, nullptr);

  EXPECT_EQ(parsed->milliamps_supported, original.milliamps_supported);
  ASSERT_EQ(parsed->strips.size(), original.strips.size());
  for (size_t i = 0; i < original.strips.size(); i++) {
    EXPECT_EQ(parsed->strips[i].led_count, original.strips[i].led_count);
    EXPECT_EQ(parsed->strips[i].RawFlags(), original.strips[i].RawFlags());
  }
  EXPECT_EQ(parsed->GetLedCount(), original.GetLedCount());
}

TEST(DeviceDescription, serializedLayoutMatchesSpec) {
  const DeviceDescription device(2350, {StripDescription(46, {})});

  uint8_t blob[DeviceDescription::kSerializedSizeV1];
  ASSERT_TRUE(device.SerializeV1(blob));

  EXPECT_EQ(blob[0], 'F');
  EXPECT_EQ(blob[1], 'F');
  EXPECT_EQ(blob[2], 'L');
  EXPECT_EQ(blob[3], 'Y');
  EXPECT_EQ(blob[4], 1);  // version
  EXPECT_EQ(blob[5], 1);  // strip_count
  EXPECT_EQ(blob[6], 0);  // reserved
  EXPECT_EQ(blob[7], 0);
  // milliamps, little-endian: 2350 = 0x092E
  EXPECT_EQ(blob[8], 0x2E);
  EXPECT_EQ(blob[9], 0x09);
  EXPECT_EQ(blob[10], 0);
  EXPECT_EQ(blob[11], 0);
  EXPECT_EQ(blob[12], 46);  // strip 0 led_count
  EXPECT_EQ(blob[13], 0);   // strip 0 flags
  for (uint8_t i = 14; i < 28; i++) {
    EXPECT_EQ(blob[i], 0) << "unused strip slot byte " << (int)i;
  }
  uint32_t stored_crc = (uint32_t)blob[28] | ((uint32_t)blob[29] << 8) |
                        ((uint32_t)blob[30] << 16) | ((uint32_t)blob[31] << 24);
  EXPECT_EQ(stored_crc, TestCrc32(blob, 28));
}

// These blobs were generated by the web configurator's implementation of the
// format, to prove browser-blob -> firmware-parse compatibility.
TEST(DeviceDescription, parsesConfiguratorGeneratedBlob) {
  // scarf: 2350 mA, one 46-LED strip, no flags
  const uint8_t scarf_blob[DeviceDescription::kSerializedSizeV1] = {
      0x46, 0x46, 0x4c, 0x59, 0x01, 0x01, 0x00, 0x00, 0x2e, 0x09, 0x00,
      0x00, 0x2e, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
      0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xce, 0x2f, 0x38, 0xd7};

  std::unique_ptr<DeviceDescription> scarf(
      DeviceDescription::FromV1(scarf_blob));
  ASSERT_NE(scarf, nullptr);
  EXPECT_EQ(scarf->milliamps_supported, 2350u);
  ASSERT_EQ(scarf->strips.size(), 1u);
  EXPECT_EQ(scarf->strips[0].led_count, 46);
  EXPECT_EQ(scarf->strips[0].RawFlags(), 0);

  // will_top_hat: 2350 mA, one 50-LED strip, Circular
  const uint8_t top_hat_blob[DeviceDescription::kSerializedSizeV1] = {
      0x46, 0x46, 0x4c, 0x59, 0x01, 0x01, 0x00, 0x00, 0x2e, 0x09, 0x00,
      0x00, 0x32, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
      0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xfb, 0xa7, 0x41, 0x1c};

  std::unique_ptr<DeviceDescription> top_hat(
      DeviceDescription::FromV1(top_hat_blob));
  ASSERT_NE(top_hat, nullptr);
  EXPECT_EQ(top_hat->milliamps_supported, 2350u);
  ASSERT_EQ(top_hat->strips.size(), 1u);
  EXPECT_EQ(top_hat->strips[0].led_count, 50);
  EXPECT_TRUE(top_hat->strips[0].FlagEnabled(Circular));
  EXPECT_FALSE(top_hat->strips[0].FlagEnabled(Tiny));
}

TEST(DeviceDescription, rejectsBadMagic) {
  const DeviceDescription device(2350, {StripDescription(46, {})});
  uint8_t blob[DeviceDescription::kSerializedSizeV1];
  ASSERT_TRUE(device.SerializeV1(blob));

  blob[0] = 'X';
  FixCrc(blob);
  EXPECT_EQ(DeviceDescription::FromV1(blob), nullptr);
}

TEST(DeviceDescription, rejectsUnknownVersion) {
  const DeviceDescription device(2350, {StripDescription(46, {})});
  uint8_t blob[DeviceDescription::kSerializedSizeV1];
  ASSERT_TRUE(device.SerializeV1(blob));

  blob[4] = 2;
  FixCrc(blob);
  EXPECT_EQ(DeviceDescription::FromV1(blob), nullptr);
}

TEST(DeviceDescription, rejectsCorruptedBlob) {
  const DeviceDescription device(2350, {StripDescription(46, {})});
  uint8_t blob[DeviceDescription::kSerializedSizeV1];
  ASSERT_TRUE(device.SerializeV1(blob));

  blob[12] = 47;  // flip the LED count without fixing the CRC
  EXPECT_EQ(DeviceDescription::FromV1(blob), nullptr);
}

TEST(DeviceDescription, rejectsErasedFlash) {
  uint8_t blob[DeviceDescription::kSerializedSizeV1];
  memset(blob, 0xFF, sizeof(blob));
  EXPECT_EQ(DeviceDescription::FromV1(blob), nullptr);

  memset(blob, 0x00, sizeof(blob));
  EXPECT_EQ(DeviceDescription::FromV1(blob), nullptr);
}

TEST(DeviceDescription, rejectsInvalidStripCounts) {
  const DeviceDescription device(2350, {StripDescription(46, {})});
  uint8_t blob[DeviceDescription::kSerializedSizeV1];
  ASSERT_TRUE(device.SerializeV1(blob));

  blob[5] = 0;
  FixCrc(blob);
  EXPECT_EQ(DeviceDescription::FromV1(blob), nullptr);

  blob[5] = DeviceDescription::kMaxStripsV1 + 1;
  FixCrc(blob);
  EXPECT_EQ(DeviceDescription::FromV1(blob), nullptr);
}

TEST(DeviceDescription, serializeRejectsUnrepresentableDevices) {
  uint8_t blob[DeviceDescription::kSerializedSizeV1];

  const DeviceDescription no_strips(2350, {});
  EXPECT_FALSE(no_strips.SerializeV1(blob));

  std::vector<StripDescription> too_many;
  for (uint8_t i = 0; i < DeviceDescription::kMaxStripsV1 + 1; i++) {
    too_many.push_back(StripDescription(16, {}));
  }
  const DeviceDescription nine_strips(2350, too_many);
  EXPECT_FALSE(nine_strips.SerializeV1(blob));
}

TEST(DeviceDescription, serializeMaxStripsRoundTrips) {
  std::vector<StripDescription> strips;
  for (uint8_t i = 0; i < DeviceDescription::kMaxStripsV1; i++) {
    strips.push_back(StripDescription(16, i % 2 ? std::vector<StripFlag>{Reversed}
                                                : std::vector<StripFlag>{}));
  }
  const DeviceDescription matrix(2350, strips);

  uint8_t blob[DeviceDescription::kSerializedSizeV1];
  ASSERT_TRUE(matrix.SerializeV1(blob));

  std::unique_ptr<DeviceDescription> parsed(DeviceDescription::FromV1(blob));
  ASSERT_NE(parsed, nullptr);
  ASSERT_EQ(parsed->strips.size(), (size_t)DeviceDescription::kMaxStripsV1);
  EXPECT_EQ(parsed->GetLedCount(), 128);
  EXPECT_FALSE(parsed->strips[0].FlagEnabled(Reversed));
  EXPECT_TRUE(parsed->strips[1].FlagEnabled(Reversed));
}

TEST(DeviceDescription, ledCountSumsZeroOneAndManyStrips) {
  EXPECT_EQ(DeviceDescription(2000, {}).GetLedCount(), 0);
  EXPECT_EQ(DeviceDescription(2000, {StripDescription(7, {})}).GetLedCount(),
            7);
  EXPECT_EQ(DeviceDescription(2000, {StripDescription(3, {}),
                                     StripDescription(5, {}),
                                     StripDescription(2, {})})
                .GetLedCount(),
            10);
}

// Pins documented current behavior, not a fix: GetLedCount accumulates into a
// uint16_t but returns uint8_t, so devices past 255 total LEDs truncate
// mod 256 (known latent limitation - the whole render path indexes LEDs with
// uint8_t). Changing this is a separate decision; this test exists so the
// change is deliberate.
TEST(DeviceDescription, ledCountAbove255TruncatesToUint8) {
  DeviceDescription device(2000,
                           {StripDescription(200, {}), StripDescription(200, {})});
  EXPECT_EQ(device.GetLedCount(), (200 + 200) % 256);
}
